version: '3'
services:
  db:
    image: mysql:8.3
    container_name: matchesstatistics_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: DockerfileBackend
    container_name: Backend
    command: sh -c "cron && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./Backend/:/app/backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: DockerfileFrontend
    container_name: Frontend
    command: sh -c "npm start"
    restart: always
    volumes:
      - ./Frontend/:/app/frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - ./Frontend/.env
    depends_on:
      - backend

volumes:
  data: