# Generated by Django 4.2.9 on 2024-01-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='players', to='players.player'),
        ),
        migrations.AlterUniqueTogether(
            name='matchscore',
            unique_together={('player', 'match')},
        ),
    ]
