# Generated by Django 4.2.9 on 2024-01-22 03:31

from django.db import migrations, models
import django.db.models.deletion
import players.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_img', serialize=False, to='players.player')),
                ('thumbnail', models.ImageField(upload_to=players.models.route)),
                ('med', models.ImageField(upload_to=players.models.route)),
                ('large', models.ImageField(upload_to=players.models.route)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='players.player')),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('last_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='matches.match')),
            ],
        ),
    ]
